### ISSUE TITLE
Website Certificate... again...

### ISSUE THREAD

**Issue by AshtonSnapp** [kamholz/latreex#4]
I know you had an issue about this previously, but the certificate expired again. According to the about:certificate page that Firefox opened up, it expired yesterday at around noon (4/4/2021 at 12:09:27 PM). Hopefully this can get fixed, as LaTreeX is an extremely useful tool for both linguistics people and conlangers (people like me who like to make up langauges).

**Comment by kamholz** [comment]
Sorry about that. Should be fixed now -- give it a try?

**Comment by AshtonSnapp** [comment]
works!
